"use client";

import Link from "next/link";
import type { GeneratedStorePage } from "@/types/store-page";

function formatPrice(amount: number, currency: string) {
  return new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency,
  }).format(amount);
}

export function GeneratedStorefront({ store }: { store: GeneratedStorePage }) {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-[#F5E6C8]">
      <header
        className="border-b border-[#3d3528]"
        style={{ borderBottomColor: `${store.primaryColor}40` }}
      >
        <div className="mx-auto flex max-w-5xl items-center justify-between gap-4 px-4 py-4 sm:px-6">
          <div className="flex items-center gap-3">
            {store.logoDataUrl ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={store.logoDataUrl}
                alt={`${store.brandName} logo`}
                className="h-10 w-10 rounded-lg"
              />
            ) : null}
            <div>
              <p className="font-semibold" style={{ color: store.accentColor }}>
                {store.brandName}
              </p>
              <p className="text-xs text-[#A89878]">{store.tagline}</p>
            </div>
          </div>
          <button
            type="button"
            className="rounded-lg px-4 py-2 text-sm font-medium text-[#0a0a0a]"
            style={{ backgroundColor: store.primaryColor }}
          >
            {store.heroCta}
          </button>
        </div>
      </header>

      <main className="mx-auto max-w-5xl px-4 py-10 sm:px-6">
        <section className="mb-10 rounded-2xl border border-[#3d3528] bg-[#101010] p-6 sm:p-8">
          <p
            className="text-xs font-semibold uppercase tracking-wider"
            style={{ color: store.primaryColor }}
          >
            Welcome
          </p>
          <h1 className="mt-2 text-2xl font-bold sm:text-3xl">{store.brandName}</h1>
          <p className="mt-3 max-w-2xl text-sm leading-relaxed text-[#A89878]">
            {store.description}
          </p>
          <button
            type="button"
            className="mt-6 rounded-lg px-5 py-2.5 text-sm font-semibold text-[#0a0a0a]"
            style={{ backgroundColor: store.primaryColor }}
          >
            {store.heroCta}
          </button>
        </section>

        <section>
          <h2 className="mb-4 text-lg font-semibold">Products</h2>
          <ul className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {store.products.map((product) => (
              <li
                key={product.id}
                className="flex flex-col rounded-xl border border-[#3d3528] bg-[#101010] p-4"
              >
                <span className="text-3xl" aria-hidden>
                  {product.imageEmoji ?? "✨"}
                </span>
                <p className="mt-3 font-medium">{product.name}</p>
                <p className="mt-1 flex-1 text-xs text-[#A89878]">{product.description}</p>
                <p className="mt-3 text-sm font-semibold" style={{ color: store.primaryColor }}>
                  {formatPrice(product.price, product.currency)}
                </p>
                <button
                  type="button"
                  className="mt-3 w-full rounded-lg border border-[#3d3528] py-2 text-xs font-medium hover:border-[#D4AF37]/40"
                >
                  Add to cart
                </button>
              </li>
            ))}
          </ul>
        </section>

        <footer className="mt-12 border-t border-[#3d3528] pt-6 text-center text-xs text-[#6B5D48]">
          <p>
            Store generated by{" "}
            <Link href="/" className="text-[#D4AF37] hover:underline">
              Aarvanta Launch OS
            </Link>
          </p>
          <p className="mt-1">Demo storefront — checkout integration coming in Milestone 2</p>
        </footer>
      </main>
    </div>
  );
}
