import type {
  SiteCategoryId,
  SiteTemplateDefinition,
  SiteTemplateSectionRecipe,
} from "@/types/site-builder";

function r(
  type: SiteTemplateSectionRecipe["type"],
  label: string,
  description: string
): SiteTemplateSectionRecipe {
  return { type, label, description };
}

const homeDense = (
  extras: SiteTemplateSectionRecipe[]
): SiteTemplateSectionRecipe[] => [
  r("hero", "Hero", "Primary value proposition and CTAs"),
  r("logo_cloud", "Social proof", "Trusted brands or partners"),
  r("features", "Highlights", "Core differentiators"),
  ...extras,
  r("testimonials", "Testimonials", "Customer or client quotes"),
  r("cta_banner", "Closing CTA", "Final conversion band"),
];

function tpl(
  partial: Omit<SiteTemplateDefinition, "sectionsByPage"> & {
    homeExtras: SiteTemplateSectionRecipe[];
    pages: SiteTemplateDefinition["sectionsByPage"];
  }
): SiteTemplateDefinition {
  const { homeExtras, pages, ...rest } = partial;
  return {
    ...rest,
    sectionsByPage: {
      home: homeDense(homeExtras),
      ...pages,
    },
  };
}

export const SITE_TEMPLATES: SiteTemplateDefinition[] = [
  // —— Ecommerce ——
  tpl({
    id: "ecom_boutique",
    categoryId: "ecommerce",
    name: "Boutique storefront",
    description: "Warm product storytelling with featured collections and soft CTAs",
    bestFor: ["DTC brands", "Gift shops", "Artisan goods"],
    siteType: "store",
    defaultTone: "friendly",
    defaultTheme: "sunset_warm",
    defaultPages: ["home", "products", "about", "contact"],
    defaultFeatures: ["ecommerce", "contact_form", "newsletter", "seo_pack"],
    defaultCta: "buy",
    imageKeywords: ["boutique", "lifestyle product", "retail store"],
    previewAccent: "#C45C26",
    homeExtras: [
      r("products", "Featured products", "Hero SKUs with prices"),
      r("gallery", "Lookbook", "Lifestyle imagery"),
      r("newsletter", "Newsletter", "Email capture"),
    ],
    pages: {
      products: [
        r("hero", "Shop hero", "Catalog introduction"),
        r("products", "Catalog", "Full product grid"),
        r("faq_accordion", "Shipping FAQ", "Delivery and returns"),
      ],
      about: [
        r("about_split", "Our story", "Brand origin"),
        r("timeline", "Milestones", "Brand journey"),
        r("team_grid", "Makers", "People behind the brand"),
      ],
      contact: [
        r("contact", "Contact", "Support and wholesale enquiries"),
      ],
    },
  }),
  tpl({
    id: "ecom_modern_grid",
    categoryId: "ecommerce",
    name: "Modern product grid",
    description: "Clean merchandising layout focused on discovery and conversion",
    bestFor: ["Fashion", "Electronics", "Homewares"],
    siteType: "store",
    defaultTone: "bold",
    defaultTheme: "minimal_light",
    defaultPages: ["home", "products", "faq", "contact"],
    defaultFeatures: ["ecommerce", "testimonials", "seo_pack"],
    defaultCta: "buy",
    imageKeywords: ["modern retail", "product photography", "shopping"],
    previewAccent: "#111827",
    homeExtras: [
      r("stats", "Store metrics", "Orders and ratings"),
      r("products", "Bestsellers", "Top products"),
      r("comparison", "Why us", "Vs alternatives"),
      r("faq_accordion", "FAQ", "Buying questions"),
    ],
    pages: {
      products: [
        r("products", "All products", "Filterable-style catalog"),
        r("cta_banner", "Sale CTA", "Promotional band"),
      ],
      faq: [r("faq_accordion", "FAQ", "Policies and shipping")],
      contact: [r("contact", "Contact", "Customer care")],
    },
  }),
  tpl({
    id: "ecom_subscription",
    categoryId: "ecommerce",
    name: "Subscription shop",
    description: "Recurring product emphasis with plans and member perks",
    bestFor: ["Boxes", "Consumables", "Memberships"],
    siteType: "store",
    defaultTone: "friendly",
    defaultTheme: "ocean_cool",
    defaultPages: ["home", "pricing", "products", "contact"],
    defaultFeatures: ["ecommerce", "newsletter", "seo_pack"],
    defaultCta: "subscribe",
    imageKeywords: ["subscription box", "unboxing", "lifestyle"],
    previewAccent: "#0E7490",
    homeExtras: [
      r("pricing_table", "Plans", "Subscription tiers"),
      r("feature_tabs", "How it works", "Subscribe flow"),
      r("products", "This month", "Current drop"),
    ],
    pages: {
      pricing: [r("pricing_table", "Plans", "Compare tiers"), r("faq_accordion", "Billing FAQ", "Cancel anytime")],
      products: [r("products", "Catalog", "Included products")],
      contact: [r("contact", "Contact", "Member support")],
    },
  }),

  // —— SaaS ——
  tpl({
    id: "saas_launch",
    categoryId: "saas",
    name: "Product launch",
    description: "Feature-led landing with social proof and pricing",
    bestFor: ["Startups", "B2B tools", "PLG products"],
    siteType: "landing",
    defaultTone: "professional",
    defaultTheme: "ocean_cool",
    defaultPages: ["home", "pricing", "about", "contact"],
    defaultFeatures: ["contact_form", "analytics", "seo_pack"],
    defaultCta: "subscribe",
    imageKeywords: ["saas dashboard", "software ui", "startup office"],
    previewAccent: "#2563EB",
    homeExtras: [
      r("feature_tabs", "Product tour", "Key workflows"),
      r("stats", "Traction", "Usage metrics"),
      r("pricing_table", "Pricing", "Plan comparison"),
      r("faq_accordion", "FAQ", "Product questions"),
    ],
    pages: {
      pricing: [r("pricing_table", "Plans", "Full pricing"), r("comparison", "Compare", "Plan differences")],
      about: [r("about_split", "Mission", "Why we built this"), r("team_grid", "Team", "Founders")],
      contact: [r("contact", "Sales", "Talk to us"), r("booking_cta", "Demo", "Book a demo")],
    },
  }),
  tpl({
    id: "saas_enterprise",
    categoryId: "saas",
    name: "Enterprise platform",
    description: "Trust-heavy layout with security, integrations, and demos",
    bestFor: ["Enterprise SaaS", "Compliance tools"],
    siteType: "landing",
    defaultTone: "professional",
    defaultTheme: "gold_navy",
    defaultPages: ["home", "pricing", "services", "contact"],
    defaultFeatures: ["booking", "contact_form", "seo_pack"],
    defaultCta: "book_call",
    imageKeywords: ["enterprise software", "security", "corporate tech"],
    previewAccent: "#1E3A5F",
    homeExtras: [
      r("logo_cloud", "Customers", "Enterprise logos"),
      r("comparison", "Capabilities", "Platform vs status quo"),
      r("timeline", "Implementation", "Rollout phases"),
      r("booking_cta", "Request demo", "Sales CTA"),
    ],
    pages: {
      pricing: [r("pricing_table", "Packages", "Enterprise tiers")],
      services: [r("services_grid", "Solutions", "Use cases"), r("feature_tabs", "Modules", "Platform modules")],
      contact: [r("contact", "Contact sales", "Form"), r("booking_cta", "Book", "Calendar CTA")],
    },
  }),
  tpl({
    id: "saas_plg",
    categoryId: "saas",
    name: "PLG growth",
    description: "Self-serve oriented with free tier and product education",
    bestFor: ["Developer tools", "SMB apps"],
    siteType: "landing",
    defaultTone: "bold",
    defaultTheme: "bold_dark",
    defaultPages: ["home", "pricing", "blog", "contact"],
    defaultFeatures: ["blog", "newsletter", "seo_pack"],
    defaultCta: "subscribe",
    imageKeywords: ["developer", "code editor", "dark ui"],
    previewAccent: "#7C3AED",
    homeExtras: [
      r("stats", "Growth", "Active users"),
      r("features", "Capabilities", "Product pillars"),
      r("pricing_table", "Free to Pro", "Self-serve plans"),
      r("blog_list", "Guides", "Educational content"),
    ],
    pages: {
      pricing: [r("pricing_table", "Plans", "Free and paid")],
      blog: [r("blog_list", "Blog", "Articles"), r("newsletter", "Subscribe", "Email")],
      contact: [r("contact", "Support", "Help form")],
    },
  }),

  // —— Local service ——
  tpl({
    id: "local_trust",
    categoryId: "local_service",
    name: "Neighbourhood trust",
    description: "Reviews, service areas, and booking for local trades",
    bestFor: ["Trades", "Home services", "Cleaning"],
    siteType: "business",
    defaultTone: "friendly",
    defaultTheme: "ocean_cool",
    defaultPages: ["home", "services", "about", "contact"],
    defaultFeatures: ["booking", "testimonials", "contact_form", "seo_pack"],
    defaultCta: "book_call",
    imageKeywords: ["local business", "home service", "technician"],
    previewAccent: "#0369A1",
    homeExtras: [
      r("services_grid", "Services", "What we offer"),
      r("stats", "Local proof", "Jobs completed"),
      r("booking_cta", "Book now", "Scheduling CTA"),
      r("faq_accordion", "FAQ", "Common questions"),
    ],
    pages: {
      services: [r("services_grid", "Services", "Detailed list"), r("pricing_table", "Pricing", "Packages")],
      about: [r("about_split", "About", "Our story"), r("team_grid", "Team", "Crew")],
      contact: [r("contact", "Get a quote", "Form"), r("booking_cta", "Book", "Call or book")],
    },
  }),
  tpl({
    id: "local_premium",
    categoryId: "local_service",
    name: "Premium local",
    description: "Elevated service branding with process and guarantees",
    bestFor: ["Premium trades", "Consultants", "Coaches"],
    siteType: "business",
    defaultTone: "luxury",
    defaultTheme: "gold_navy",
    defaultPages: ["home", "services", "testimonials", "contact"],
    defaultFeatures: ["booking", "testimonials", "seo_pack"],
    defaultCta: "book_call",
    imageKeywords: ["premium service", "consultation", "luxury interior"],
    previewAccent: "#B8965D",
    homeExtras: [
      r("timeline", "Process", "How engagements work"),
      r("services_grid", "Offerings", "Service menu"),
      r("gallery", "Work", "Before/after style gallery"),
    ],
    pages: {
      services: [r("services_grid", "Services", "Detailed"), r("comparison", "Packages", "Compare")],
      testimonials: [r("testimonials", "Reviews", "Client feedback"), r("stats", "Outcomes", "Results")],
      contact: [r("booking_cta", "Book", "Consultation"), r("contact", "Contact", "Form")],
    },
  }),

  // —— Professional ——
  tpl({
    id: "pro_authority",
    categoryId: "professional",
    name: "Authority practice",
    description: "Credential-led layout for firms that sell expertise",
    bestFor: ["Law", "Accounting", "Advisory"],
    siteType: "business",
    defaultTone: "professional",
    defaultTheme: "gold_navy",
    defaultPages: ["home", "services", "about", "contact"],
    defaultFeatures: ["contact_form", "booking", "seo_pack"],
    defaultCta: "book_call",
    imageKeywords: ["law office", "professional meeting", "boardroom"],
    previewAccent: "#1B2A41",
    homeExtras: [
      r("services_grid", "Practice areas", "Expertise"),
      r("team_grid", "Partners", "Leadership"),
      r("timeline", "Approach", "Engagement steps"),
      r("stats", "Track record", "Outcomes"),
    ],
    pages: {
      services: [r("services_grid", "Services", "Practice areas"), r("faq_accordion", "FAQ", "Client questions")],
      about: [r("about_split", "Firm", "Heritage"), r("team_grid", "People", "Team")],
      contact: [r("contact", "Enquire", "Form"), r("booking_cta", "Consultation", "Book")],
    },
  }),
  tpl({
    id: "pro_modern_firm",
    categoryId: "professional",
    name: "Modern firm",
    description: "Cleaner, approachable professional services brand",
    bestFor: ["Consultancies", "Boutique firms"],
    siteType: "business",
    defaultTone: "professional",
    defaultTheme: "minimal_light",
    defaultPages: ["home", "services", "blog", "contact"],
    defaultFeatures: ["blog", "contact_form", "seo_pack"],
    defaultCta: "contact",
    imageKeywords: ["modern office", "consultancy", "whiteboard"],
    previewAccent: "#334155",
    homeExtras: [
      r("feature_tabs", "Capabilities", "Service pillars"),
      r("blog_list", "Insights", "Thought leadership"),
      r("cta_banner", "Talk to us", "Lead CTA"),
    ],
    pages: {
      services: [r("services_grid", "Services", "Offerings")],
      blog: [r("blog_list", "Insights", "Articles")],
      contact: [r("contact", "Contact", "Form")],
    },
  }),

  // —— Restaurant ——
  tpl({
    id: "resto_ambiance",
    categoryId: "restaurant",
    name: "Ambience dining",
    description: "Visual-first hospitality with menu and reservation CTAs",
    bestFor: ["Restaurants", "Bars", "Cafés"],
    siteType: "business",
    defaultTone: "luxury",
    defaultTheme: "bold_dark",
    defaultPages: ["home", "services", "about", "contact"],
    defaultFeatures: ["booking", "contact_form", "seo_pack"],
    defaultCta: "book_call",
    imageKeywords: ["restaurant interior", "plated food", "dining"],
    previewAccent: "#9A3412",
    homeExtras: [
      r("menu_list", "Signature dishes", "Menu highlights"),
      r("gallery", "Atmosphere", "Venue photos"),
      r("booking_cta", "Reserve", "Table booking"),
    ],
    pages: {
      services: [r("menu_list", "Full menu", "Courses"), r("gallery", "Gallery", "Food photos")],
      about: [r("about_split", "Our kitchen", "Story"), r("team_grid", "Chefs", "Team")],
      contact: [r("booking_cta", "Reservations", "Book a table"), r("contact", "Private dining", "Enquiry")],
    },
  }),
  tpl({
    id: "resto_casual",
    categoryId: "restaurant",
    name: "Casual eatery",
    description: "Friendly menu-forward site for everyday dining",
    bestFor: ["Cafés", "Brunch", "Fast-casual"],
    siteType: "business",
    defaultTone: "friendly",
    defaultTheme: "sunset_warm",
    defaultPages: ["home", "services", "faq", "contact"],
    defaultFeatures: ["booking", "newsletter", "seo_pack"],
    defaultCta: "book_call",
    imageKeywords: ["cafe", "brunch", "coffee shop"],
    previewAccent: "#EA580C",
    homeExtras: [
      r("menu_list", "Menu", "Popular items"),
      r("stats", "Favourites", "Guest stats"),
      r("newsletter", "Updates", "Events and specials"),
    ],
    pages: {
      services: [r("menu_list", "Menu", "Full list")],
      faq: [r("faq_accordion", "Visit FAQ", "Hours and allergens")],
      contact: [r("contact", "Contact", "Location and form"), r("booking_cta", "Book", "Reserve")],
    },
  }),

  // —— Healthcare ——
  tpl({
    id: "health_clinic",
    categoryId: "healthcare",
    name: "Modern clinic",
    description: "Calm care site with treatments and appointment booking",
    bestFor: ["Dental", "GP", "Physio"],
    siteType: "business",
    defaultTone: "professional",
    defaultTheme: "ocean_cool",
    defaultPages: ["home", "services", "about", "contact"],
    defaultFeatures: ["booking", "testimonials", "contact_form", "seo_pack"],
    defaultCta: "book_call",
    imageKeywords: ["modern clinic", "healthcare", "dental office"],
    previewAccent: "#0891B2",
    homeExtras: [
      r("services_grid", "Treatments", "Care menu"),
      r("stats", "Patient care", "Trust metrics"),
      r("team_grid", "Clinicians", "Care team"),
      r("booking_cta", "Book visit", "Appointments"),
      r("faq_accordion", "Patient FAQ", "Visit prep"),
    ],
    pages: {
      services: [r("services_grid", "Treatments", "Detailed"), r("pricing_table", "Fees", "Transparent pricing")],
      about: [r("about_split", "Clinic", "Philosophy"), r("team_grid", "Team", "Staff")],
      contact: [r("booking_cta", "Book", "Appointment"), r("contact", "Contact", "Form")],
    },
  }),
  tpl({
    id: "health_wellness",
    categoryId: "healthcare",
    name: "Wellness studio",
    description: "Warm wellness branding with programmes and memberships",
    bestFor: ["Therapy", "Wellness", "Mental health"],
    siteType: "business",
    defaultTone: "friendly",
    defaultTheme: "minimal_light",
    defaultPages: ["home", "services", "pricing", "contact"],
    defaultFeatures: ["booking", "newsletter", "seo_pack"],
    defaultCta: "book_call",
    imageKeywords: ["wellness", "therapy room", "calm spa"],
    previewAccent: "#059669",
    homeExtras: [
      r("feature_tabs", "Programmes", "Care paths"),
      r("testimonials", "Stories", "Client voices"),
      r("pricing_table", "Sessions", "Pricing"),
    ],
    pages: {
      services: [r("services_grid", "Programmes", "Offerings")],
      pricing: [r("pricing_table", "Pricing", "Sessions and packs")],
      contact: [r("booking_cta", "Book", "Session"), r("contact", "Contact", "Form")],
    },
  }),

  // —— Agency ——
  tpl({
    id: "agency_casework",
    categoryId: "agency",
    name: "Casework studio",
    description: "Portfolio-led agency site with process and leads",
    bestFor: ["Design agencies", "Marketing shops"],
    siteType: "business",
    defaultTone: "bold",
    defaultTheme: "bold_dark",
    defaultPages: ["home", "portfolio", "services", "contact"],
    defaultFeatures: ["contact_form", "testimonials", "seo_pack"],
    defaultCta: "contact",
    imageKeywords: ["creative agency", "design studio", "branding"],
    previewAccent: "#7C3AED",
    homeExtras: [
      r("portfolio_grid", "Selected work", "Case studies"),
      r("timeline", "Process", "How we work"),
      r("services_grid", "Capabilities", "Services"),
      r("stats", "Impact", "Results"),
    ],
    pages: {
      portfolio: [r("portfolio_grid", "Work", "Projects"), r("testimonials", "Clients", "Quotes")],
      services: [r("services_grid", "Services", "Capabilities"), r("pricing_table", "Engagements", "Retainer options")],
      contact: [r("contact", "Start a project", "Brief form")],
    },
  }),
  tpl({
    id: "agency_growth",
    categoryId: "agency",
    name: "Growth partner",
    description: "Outcomes-focused agency with offers and proof",
    bestFor: ["Performance marketing", "Growth consultancies"],
    siteType: "business",
    defaultTone: "professional",
    defaultTheme: "ocean_cool",
    defaultPages: ["home", "services", "about", "contact"],
    defaultFeatures: ["booking", "testimonials", "seo_pack"],
    defaultCta: "book_call",
    imageKeywords: ["marketing analytics", "growth team", "strategy"],
    previewAccent: "#0284C7",
    homeExtras: [
      r("comparison", "Before / after", "Outcomes framing"),
      r("services_grid", "Offers", "Service packages"),
      r("logo_cloud", "Clients", "Brand logos"),
      r("booking_cta", "Strategy call", "Book"),
    ],
    pages: {
      services: [r("services_grid", "Services", "Packages"), r("feature_tabs", "Playbooks", "Methods")],
      about: [r("about_split", "About", "Philosophy"), r("team_grid", "Team", "Operators")],
      contact: [r("booking_cta", "Book", "Call"), r("contact", "Contact", "Form")],
    },
  }),

  // —— Portfolio ——
  tpl({
    id: "folio_editorial",
    categoryId: "portfolio",
    name: "Editorial portfolio",
    description: "Typography-led gallery for visual and spatial work",
    bestFor: ["Architects", "Photographers", "Artists"],
    siteType: "portfolio",
    defaultTone: "luxury",
    defaultTheme: "minimal_light",
    defaultPages: ["home", "portfolio", "about", "contact"],
    defaultFeatures: ["contact_form", "seo_pack"],
    defaultCta: "contact",
    imageKeywords: ["architecture", "editorial photography", "gallery"],
    previewAccent: "#57534E",
    homeExtras: [
      r("portfolio_grid", "Selected projects", "Featured work"),
      r("gallery", "Studies", "Image essays"),
      r("about_split", "Practice", "Short bio"),
    ],
    pages: {
      portfolio: [r("portfolio_grid", "Projects", "Full grid"), r("gallery", "Archive", "More work")],
      about: [r("about_split", "About", "Bio"), r("timeline", "Career", "Milestones")],
      contact: [r("contact", "Commissions", "Enquiry")],
    },
  }),
  tpl({
    id: "folio_freelancer",
    categoryId: "portfolio",
    name: "Freelancer showcase",
    description: "Skills, samples, and hire CTA for independents",
    bestFor: ["Freelancers", "Consultants", "Creators"],
    siteType: "portfolio",
    defaultTone: "friendly",
    defaultTheme: "ocean_cool",
    defaultPages: ["home", "portfolio", "services", "contact"],
    defaultFeatures: ["contact_form", "booking", "seo_pack"],
    defaultCta: "book_call",
    imageKeywords: ["freelancer workspace", "creative desk", "portfolio"],
    previewAccent: "#0D9488",
    homeExtras: [
      r("features", "Skills", "Capabilities"),
      r("portfolio_grid", "Work", "Samples"),
      r("pricing_table", "Rates", "Engagement options"),
      r("booking_cta", "Hire me", "Availability"),
    ],
    pages: {
      portfolio: [r("portfolio_grid", "Work", "Projects")],
      services: [r("services_grid", "Services", "Offers"), r("pricing_table", "Rates", "Pricing")],
      contact: [r("contact", "Contact", "Form"), r("booking_cta", "Book", "Intro call")],
    },
  }),

  // —— Nonprofit ——
  tpl({
    id: "nonprofit_mission",
    categoryId: "nonprofit",
    name: "Mission forward",
    description: "Impact storytelling with programmes and donate CTAs",
    bestFor: ["Charities", "Foundations", "Community orgs"],
    siteType: "business",
    defaultTone: "friendly",
    defaultTheme: "sunset_warm",
    defaultPages: ["home", "about", "services", "contact"],
    defaultFeatures: ["newsletter", "contact_form", "seo_pack"],
    defaultCta: "contact",
    imageKeywords: ["community", "volunteers", "nonprofit"],
    previewAccent: "#C2410C",
    homeExtras: [
      r("stats", "Impact", "Lives reached"),
      r("services_grid", "Programmes", "Initiatives"),
      r("timeline", "Journey", "Milestones"),
      r("cta_banner", "Donate / join", "Support CTA"),
      r("newsletter", "Stay close", "Updates"),
    ],
    pages: {
      about: [r("about_split", "Mission", "Why we exist"), r("team_grid", "People", "Team")],
      services: [r("services_grid", "Programmes", "What we run"), r("gallery", "In the field", "Photos")],
      contact: [r("contact", "Get involved", "Form"), r("cta_banner", "Donate", "Support")],
    },
  }),
  tpl({
    id: "nonprofit_campaign",
    categoryId: "nonprofit",
    name: "Campaign hub",
    description: "Urgent campaign layout with goals and volunteer paths",
    bestFor: ["Fundraisers", "Advocacy", "Drives"],
    siteType: "landing",
    defaultTone: "bold",
    defaultTheme: "bold_dark",
    defaultPages: ["home", "about", "faq", "contact"],
    defaultFeatures: ["newsletter", "contact_form", "seo_pack"],
    defaultCta: "subscribe",
    imageKeywords: ["protest", "fundraising", "community action"],
    previewAccent: "#DC2626",
    homeExtras: [
      r("stats", "Campaign goals", "Progress"),
      r("feature_tabs", "Ways to help", "Actions"),
      r("testimonials", "Voices", "Community quotes"),
      r("cta_banner", "Act now", "Primary ask"),
    ],
    pages: {
      about: [r("about_split", "The cause", "Context"), r("timeline", "Campaign", "Timeline")],
      faq: [r("faq_accordion", "FAQ", "Common questions")],
      contact: [r("contact", "Volunteer", "Signup"), r("newsletter", "Updates", "Email")],
    },
  }),

  // —— Blog ——
  tpl({
    id: "blog_magazine",
    categoryId: "blog",
    name: "Magazine",
    description: "Editorial homepage with featured stories and topics",
    bestFor: ["Publications", "Media brands"],
    siteType: "landing",
    defaultTone: "professional",
    defaultTheme: "minimal_light",
    defaultPages: ["home", "blog", "about", "contact"],
    defaultFeatures: ["blog", "newsletter", "seo_pack"],
    defaultCta: "subscribe",
    imageKeywords: ["magazine", "editorial desk", "writing"],
    previewAccent: "#1F2937",
    homeExtras: [
      r("blog_list", "Featured", "Top stories"),
      r("feature_tabs", "Topics", "Sections"),
      r("newsletter", "Subscribe", "Email"),
      r("team_grid", "Writers", "Contributors"),
    ],
    pages: {
      blog: [r("blog_list", "All posts", "Archive"), r("newsletter", "Subscribe", "Email")],
      about: [r("about_split", "About", "Masthead"), r("team_grid", "Team", "Editors")],
      contact: [r("contact", "Tips / press", "Form")],
    },
  }),
  tpl({
    id: "blog_newsletter",
    categoryId: "blog",
    name: "Newsletter brand",
    description: "Conversion-focused content brand with archive and signup",
    bestFor: ["Solo writers", "Niche newsletters"],
    siteType: "landing",
    defaultTone: "friendly",
    defaultTheme: "ocean_cool",
    defaultPages: ["home", "blog", "pricing", "contact"],
    defaultFeatures: ["blog", "newsletter", "seo_pack"],
    defaultCta: "subscribe",
    imageKeywords: ["newsletter", "laptop writing", "coffee desk"],
    previewAccent: "#2563EB",
    homeExtras: [
      r("stats", "Readers", "Audience size"),
      r("blog_list", "Recent issues", "Archive"),
      r("pricing_table", "Membership", "Free vs paid"),
      r("newsletter", "Join", "Signup"),
    ],
    pages: {
      blog: [r("blog_list", "Archive", "Issues")],
      pricing: [r("pricing_table", "Membership", "Tiers"), r("faq_accordion", "FAQ", "Billing")],
      contact: [r("contact", "Contact", "Form")],
    },
  }),

  // —— Event ——
  tpl({
    id: "event_conference",
    categoryId: "event",
    name: "Conference",
    description: "Agenda, speakers, and ticket CTAs for multi-day events",
    bestFor: ["Conferences", "Summits"],
    siteType: "landing",
    defaultTone: "bold",
    defaultTheme: "bold_dark",
    defaultPages: ["home", "about", "pricing", "contact"],
    defaultFeatures: ["contact_form", "newsletter", "seo_pack"],
    defaultCta: "buy",
    imageKeywords: ["conference stage", "audience", "keynote"],
    previewAccent: "#4F46E5",
    homeExtras: [
      r("stats", "Event facts", "Attendees and stages"),
      r("team_grid", "Speakers", "Line-up"),
      r("timeline", "Agenda", "Day schedule"),
      r("pricing_table", "Tickets", "Passes"),
      r("faq_accordion", "Attendee FAQ", "Logistics"),
    ],
    pages: {
      about: [r("about_split", "About the event", "Vision"), r("team_grid", "Speakers", "Full list"), r("gallery", "Past years", "Photos")],
      pricing: [r("pricing_table", "Tickets", "Passes"), r("cta_banner", "Register", "Buy tickets")],
      contact: [r("contact", "Partnerships", "Sponsors form")],
    },
  }),
  tpl({
    id: "event_workshop",
    categoryId: "event",
    name: "Workshop series",
    description: "Intimate event layout for courses and meetups",
    bestFor: ["Workshops", "Meetups", "Classes"],
    siteType: "landing",
    defaultTone: "friendly",
    defaultTheme: "sunset_warm",
    defaultPages: ["home", "services", "faq", "contact"],
    defaultFeatures: ["booking", "newsletter", "seo_pack"],
    defaultCta: "book_call",
    imageKeywords: ["workshop", "classroom", "community meetup"],
    previewAccent: "#D97706",
    homeExtras: [
      r("feature_tabs", "Sessions", "Formats"),
      r("timeline", "Schedule", "Upcoming dates"),
      r("pricing_table", "Seats", "Ticket prices"),
      r("booking_cta", "Reserve a seat", "Register"),
    ],
    pages: {
      services: [r("services_grid", "Workshops", "Catalogue"), r("timeline", "Calendar", "Dates")],
      faq: [r("faq_accordion", "FAQ", "Attendance")],
      contact: [r("contact", "Host / sponsor", "Form"), r("booking_cta", "Book", "Seat")],
    },
  }),

  // —— Internal tool landing ——
  tpl({
    id: "tool_ops",
    categoryId: "internal_tool_landing",
    name: "Ops platform",
    description: "Internal product marketing for operations tooling",
    bestFor: ["Ops tools", "Internal platforms"],
    siteType: "landing",
    defaultTone: "professional",
    defaultTheme: "ocean_cool",
    defaultPages: ["home", "services", "pricing", "contact"],
    defaultFeatures: ["contact_form", "analytics", "seo_pack"],
    defaultCta: "subscribe",
    imageKeywords: ["operations dashboard", "workflow software", "team ops"],
    previewAccent: "#0F766E",
    homeExtras: [
      r("feature_tabs", "Modules", "Ops workflows"),
      r("comparison", "Before / after", "Process gains"),
      r("stats", "Efficiency", "Time saved"),
      r("pricing_table", "Seats", "Internal pricing"),
    ],
    pages: {
      services: [r("services_grid", "Modules", "Capabilities"), r("feature_tabs", "Workflows", "Detailed")],
      pricing: [r("pricing_table", "Plans", "Seat-based")],
      contact: [r("contact", "Request access", "Form"), r("booking_cta", "Onboarding", "Walkthrough")],
    },
  }),
  tpl({
    id: "tool_hr",
    categoryId: "internal_tool_landing",
    name: "People platform",
    description: "HR / people-tool landing with journeys and benefits",
    bestFor: ["HRIS", "Onboarding", "Intranet"],
    siteType: "landing",
    defaultTone: "friendly",
    defaultTheme: "minimal_light",
    defaultPages: ["home", "about", "faq", "contact"],
    defaultFeatures: ["contact_form", "newsletter", "seo_pack"],
    defaultCta: "contact",
    imageKeywords: ["hr software", "people team", "onboarding"],
    previewAccent: "#4F46E5",
    homeExtras: [
      r("features", "Employee journeys", "Moments that matter"),
      r("timeline", "Lifecycle", "Hire to retire"),
      r("testimonials", "Teams", "Internal quotes"),
      r("faq_accordion", "IT FAQ", "Security and SSO"),
    ],
    pages: {
      about: [r("about_split", "Built for people teams", "Story"), r("team_grid", "Champions", "Stakeholders")],
      faq: [r("faq_accordion", "FAQ", "Rollout")],
      contact: [r("contact", "Pilot request", "Form")],
    },
  }),
];

export function listTemplates(): SiteTemplateDefinition[] {
  return SITE_TEMPLATES;
}

export function getTemplatesForCategory(
  categoryId: SiteCategoryId
): SiteTemplateDefinition[] {
  return SITE_TEMPLATES.filter((t) => t.categoryId === categoryId);
}

export function getTemplateById(id: string): SiteTemplateDefinition | undefined {
  return SITE_TEMPLATES.find((t) => t.id === id);
}
