export const PRICING_TIERS = [
  {
    id: "starter",
    name: "Starter",
    price: "£49",
    period: "/month",
    description: "For solo founders and small teams getting started.",
    features: [
      "Unified inbox (5 channels)",
      "CRM contacts & leads",
      "3 AI employees",
      "Knowledge Hub (5 GB)",
      "1 workspace",
    ],
    cta: "Start free trial",
    highlighted: false,
  },
  {
    id: "growth",
    name: "Growth",
    price: "£149",
    period: "/month",
    description: "For growing SMEs ready to deploy an AI workforce.",
    features: [
      "Full AI Workforce (5 agents)",
      "CRM pipelines & lead scoring",
      "Knowledge Hub + RAG Ask",
      "Project management",
      "Workflow automation (basic)",
      "3 workspaces",
    ],
    cta: "Start free trial",
    highlighted: true,
  },
  {
    id: "scale",
    name: "Scale",
    price: "£399",
    period: "/month",
    description: "For teams scaling operations across departments.",
    features: [
      "Everything in Growth",
      "Advanced analytics",
      "Integrations hub",
      "Priority AI models",
      "10 workspaces",
      "RBAC & audit logs",
    ],
    cta: "Contact sales",
    highlighted: false,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: "Custom",
    period: "",
    description: "For organisations needing SSO, governance, and SLA.",
    features: [
      "Everything in Scale",
      "Enterprise SSO (SAML/OIDC)",
      "Multi-region & data residency",
      "Dedicated success manager",
      "Custom AI agents",
      "Unlimited workspaces",
    ],
    cta: "Talk to us",
    highlighted: false,
  },
] as const;

export const COMPANY = {
  name: "Aarvanta Limited",
  tagline: "The AI Workforce & Business Operating System",
  email: "hello@aarvanta.com",
  location: "United Kingdom",
};
