import type { LaunchLegalDoc, LaunchLegalDocType } from "@/types/launch";

function docTitle(type: LaunchLegalDocType, brandName: string): string {
  const map: Record<LaunchLegalDocType, string> = {
    terms: `${brandName} — Terms & Conditions`,
    privacy: `${brandName} — Privacy Policy`,
    cookie_policy: `${brandName} — Cookie Policy`,
  };
  return map[type];
}

export function generateLaunchLegalDocs(input: {
  brandName: string;
  countryBase: string;
  businessIdea: string;
  contactEmail?: string;
}): LaunchLegalDoc[] {
  const email = input.contactEmail ?? `hello@${input.brandName.toLowerCase().replace(/\s+/g, "")}.co.uk`;
  const date = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const terms = `# Terms & Conditions

**${input.brandName}**  
Effective date: ${date}  
Governing law: ${input.countryBase === "UK" ? "England and Wales" : input.countryBase}

## 1. Introduction
These Terms govern your use of ${input.brandName}'s website and purchase of products or services described as: *${input.businessIdea}*.

## 2. Orders & Payment
All orders are subject to acceptance. Prices include VAT where applicable at the UK standard rate. Payment is due at checkout unless otherwise agreed.

## 3. Delivery
We aim to dispatch orders within 3–5 business days. Delivery times vary by destination.

## 4. Returns & Refunds
You may return unused items within 14 days of receipt (Consumer Contracts Regulations 2013). Contact ${email} to arrange returns.

## 5. Limitation of Liability
To the fullest extent permitted by law, ${input.brandName}'s liability is limited to the purchase price of the goods or services.

## 6. Contact
Questions: ${email}

---
*Draft generated by Aarvanta Launch OS — review with qualified legal counsel before publishing.*`;

  const privacy = `# Privacy Policy

**${input.brandName}**  
Effective date: ${date}

## Data Controller
${input.brandName} is the data controller for personal data collected through our website and services.

## Data We Collect
- Contact details (name, email, address, phone)
- Order and payment information
- Website usage data and cookies

## Legal Basis (UK GDPR)
We process data based on contract performance, legitimate interests, and consent where required.

## Your Rights
You have the right to access, rectify, erase, restrict, and port your data. Contact ${email}.

## Retention
We retain order data for 6 years for tax purposes; marketing data until you unsubscribe.

## International Transfers
Where data is transferred outside the UK, appropriate safeguards are applied.

---
*Draft generated by Aarvanta Launch OS — review with qualified legal counsel before publishing.*`;

  const cookies = `# Cookie Policy

**${input.brandName}**  
Effective date: ${date}

We use essential cookies for checkout and session management, and analytics cookies to improve our store (with your consent).

Manage preferences via your browser or our cookie banner.

Contact: ${email}

---
*Draft generated by Aarvanta Launch OS.*`;

  return [
    { type: "terms", title: docTitle("terms", input.brandName), content: terms },
    { type: "privacy", title: docTitle("privacy", input.brandName), content: privacy },
    { type: "cookie_policy", title: docTitle("cookie_policy", input.brandName), content: cookies },
  ];
}
