import { NextResponse } from "next/server";
import { getProposalStore } from "@/lib/data/platform-store";
import { getTenantScope } from "@/lib/tenant/context";

function proposalDocument(proposal: {
  title: string;
  clientName: string;
  value: number;
  currency: string;
  content: string;
  brandingOrg: string;
  status: string;
  createdAt: string;
}) {
  const value = new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency: proposal.currency || "GBP",
  }).format(proposal.value);

  return `# ${proposal.title}

**Prepared for:** ${proposal.clientName}  
**Prepared by:** ${proposal.brandingOrg}  
**Date:** ${new Date(proposal.createdAt).toLocaleDateString("en-GB")}  
**Value:** ${value}  
**Status:** ${proposal.status}

---

${proposal.content || "Proposal details to be finalised."}

---

*Generated by Aarvanta OS — Proposal Engine*
`;
}

function proposalHtml(proposal: Parameters<typeof proposalDocument>[0]) {
  const body = proposalDocument(proposal)
    .replace(/^# (.+)$/m, "<h1>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/^---$/gm, "<hr />")
    .replace(/\n/g, "<br />");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${proposal.title}</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 720px; margin: 2rem auto; color: #111; line-height: 1.6; }
    h1 { color: #94784A; }
    hr { border: none; border-top: 1px solid #ddd; margin: 1.5rem 0; }
  </style>
</head>
<body>${body}</body>
</html>`;
}

export async function GET(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const scope = await getTenantScope();
  const { id } = await params;
  const format = new URL(req.url).searchParams.get("format") ?? "pdf";

  const proposal = await getProposalStore().get(id, scope);
  if (!proposal) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const filename = `${proposal.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-${proposal.clientName.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}`;

  if (format === "docx" || format === "md") {
    const markdown = proposalDocument(proposal);
    return new NextResponse(markdown, {
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
        "Content-Disposition": `attachment; filename="${filename}.md"`,
      },
    });
  }

  const html = proposalHtml(proposal);
  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `inline; filename="${filename}.html"`,
    },
  });
}
