import type { LucideIcon } from "lucide-react";
import {
  BarChart3,
  Bell,
  BookOpen,
  Brain,
  Building2,
  CreditCard,
  FileText,
  Globe,
  Hammer,
  Inbox,
  Kanban,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  Lock,
  MessageCircle,
  PenLine,
  Phone,
  Plug,
  Rocket,
  ScrollText,
  Shield,
  ShoppingBag,
  Sparkles,
  Store,
  Users,
  Video,
  Wallet,
  Workflow,
} from "lucide-react";

export type PlatformModule = {
  id: string;
  label: string;
  description: string;
  href: string;
  icon: LucideIcon;
  group: "Core" | "Revenue" | "Intelligence" | "Operations" | "Enterprise";
  phase: number | string;
};

/** Phase 1–10 modules from os-new.txt */
export const CORE_MODULES: PlatformModule[] = [
  {
    id: "dashboard",
    label: "Founder Dashboard",
    description: "Revenue, pipeline, projects, AI workforce, Copilot",
    href: "/dashboard",
    icon: LayoutDashboard,
    group: "Core",
    phase: 12,
  },
  {
    id: "help",
    label: "Help & Product Tour",
    description: "Guided tour and 90-second live demo from the header",
    href: "/dashboard?help=open",
    icon: Sparkles,
    group: "Core",
    phase: "help",
  },
  {
    id: "workforce",
    label: "AI Workforce",
    description: "7 AI employees — profiles, memory, chat, tasks",
    href: "/workforce",
    icon: Sparkles,
    group: "Core",
    phase: 1,
  },
  {
    id: "knowledge",
    label: "Knowledge Hub",
    description: "Upload, search, RAG Ask, Company Brain",
    href: "/knowledge",
    icon: Brain,
    group: "Core",
    phase: 2,
  },
  {
    id: "crm",
    label: "CRM",
    description: "Leads, contacts, deals, AI scoring",
    href: "/crm",
    icon: Building2,
    group: "Core",
    phase: 3,
  },
  {
    id: "whatsapp",
    label: "WhatsApp OS",
    description: "WhatsApp business inbox, outbound, and webhooks",
    href: "/whatsapp",
    icon: MessageCircle,
    group: "Core",
    phase: "9b-wa",
  },
  {
    id: "calling",
    label: "Calling",
    description: "Twilio voice calls & history",
    href: "/calling",
    icon: Phone,
    group: "Core",
    phase: "9b",
  },
  {
    id: "inbox",
    label: "Unified Inbox",
    description: "Legacy multi-channel inbox (hidden from primary nav)",
    href: "/inbox",
    icon: Inbox,
    group: "Core",
    phase: "9b",
  },
  {
    id: "voice",
    label: "Voice OS",
    description: "AI calling, call log, and Twilio voice",
    href: "/voice",
    icon: Phone,
    group: "Core",
    phase: "9b-voice",
  },
  {
    id: "projects",
    label: "Project OS",
    description: "Kanban boards, tasks, delivery tracking",
    href: "/projects",
    icon: Kanban,
    group: "Core",
    phase: "1b",
  },
  {
    id: "workflows",
    label: "Workflows",
    description: "Trigger → agent → approval → action",
    href: "/workflows",
    icon: Workflow,
    group: "Core",
    phase: "1c",
  },
  {
    id: "build",
    label: "Build OS",
    description: "Site preferences → AI plan → approve before generation",
    href: "/build",
    icon: Hammer,
    group: "Core",
    phase: "siteos-1",
  },
  {
    id: "launch",
    label: "Launch OS",
    description: "Idea → full business OS — industry, buddies, workflows (AGEB V11)",
    href: "/launch",
    icon: Rocket,
    group: "Core",
    phase: "ageb-11",
  },
  {
    id: "team",
    label: "Team",
    description: "Directory, channels, notes, activity",
    href: "/team",
    icon: Users,
    group: "Core",
    phase: 6,
  },
  {
    id: "integrations",
    label: "Integrations",
    description: "Gmail, Slack, Stripe, WhatsApp connections",
    href: "/integrations",
    icon: Plug,
    group: "Core",
    phase: 8,
  },
  {
    id: "communications",
    label: "Communications",
    description: "Notifications, alerts, AI digest",
    href: "/communications",
    icon: Bell,
    group: "Core",
    phase: 9,
  },
  {
    id: "analytics",
    label: "Analytics",
    description: "Revenue, pipeline, projects, AI usage",
    href: "/analytics",
    icon: BarChart3,
    group: "Core",
    phase: 10,
  },
  {
    id: "settings",
    label: "Settings & RBAC",
    description: "Organizations, workspaces, roles",
    href: "/settings",
    icon: Shield,
    group: "Core",
    phase: 5,
  },
];

export const PLATFORM_MODULES: PlatformModule[] = [
  {
    id: "billing",
    label: "Billing",
    description: "Plans, subscriptions, usage tracking, and trials",
    href: "/billing",
    icon: CreditCard,
    group: "Revenue",
    phase: 11,
  },
  {
    id: "writing",
    label: "AI Writing Studio",
    description: "Proposals, emails, blogs, LinkedIn posts, SOPs",
    href: "/writing",
    icon: PenLine,
    group: "Intelligence",
    phase: 13,
  },
  {
    id: "meetings",
    label: "Meetings",
    description: "Transcript upload, summaries, tasks, follow-ups",
    href: "/meetings",
    icon: Video,
    group: "Intelligence",
    phase: 14,
  },
  {
    id: "knowledge-graph",
    label: "Knowledge Graph",
    description: "Entity relationships and source references",
    href: "/knowledge/graph",
    icon: Brain,
    group: "Intelligence",
    phase: 15,
  },
  {
    id: "sops",
    label: "SOP Engine",
    description: "Create, store, execute, and version SOPs",
    href: "/sops",
    icon: ScrollText,
    group: "Operations",
    phase: 18,
  },
  {
    id: "proposals",
    label: "Proposals",
    description: "Sales proposals with branding and export",
    href: "/proposals",
    icon: FileText,
    group: "Revenue",
    phase: 19,
  },
  {
    id: "portal",
    label: "Client Portal",
    description: "Customer access to projects, docs, and messages",
    href: "/portal",
    icon: Users,
    group: "Revenue",
    phase: 20,
  },
  {
    id: "templates",
    label: "Templates",
    description: "Proposals, SOPs, campaigns, workflows, contracts",
    href: "/templates",
    icon: BookOpen,
    group: "Operations",
    phase: 22,
  },
  {
    id: "memory",
    label: "Memory Layers",
    description: "User, team, company, and customer memory",
    href: "/memory",
    icon: Brain,
    group: "Intelligence",
    phase: 23,
  },
  {
    id: "success",
    label: "Customer Success",
    description: "Health scores, renewals, NPS, churn prediction",
    href: "/success",
    icon: Users,
    group: "Revenue",
    phase: 24,
  },
  {
    id: "wiki",
    label: "Internal Wiki",
    description: "Handbook, department knowledge, training content",
    href: "/wiki",
    icon: BookOpen,
    group: "Operations",
    phase: 25,
  },
  {
    id: "governance",
    label: "Governance",
    description: "Audit trail, activity logs, permission management",
    href: "/governance",
    icon: Shield,
    group: "Enterprise",
    phase: 26,
  },
  {
    id: "finance",
    label: "Finance OS",
    description: "Ledger, P&L, balance sheet, invoices, budgets, AI CFO",
    href: "/finance",
    icon: Wallet,
    group: "Revenue",
    phase: 28,
  },
  {
    id: "payroll",
    label: "Payroll OS",
    description: "UK PAYE/NI payroll runs, payslips, ledger posting",
    href: "/payroll",
    icon: Landmark,
    group: "Operations",
    phase: "ageb-3",
  },
  {
    id: "legal",
    label: "Legal OS",
    description: "Contract templates, clause analysis, risk scoring",
    href: "/legal",
    icon: ScrollText,
    group: "Enterprise",
    phase: "ageb-3",
  },
  {
    id: "hr",
    label: "HR OS",
    description: "ATS, onboarding, performance, learning",
    href: "/hr",
    icon: Landmark,
    group: "Operations",
    phase: 29,
  },
  {
    id: "autonomous",
    label: "Autonomous Agents",
    description: "Planning, delegation, task queue, agent hierarchy",
    href: "/workforce/autonomous",
    icon: Sparkles,
    group: "Intelligence",
    phase: 30,
  },
  {
    id: "sso",
    label: "Enterprise SSO",
    description: "SAML, OIDC, OAuth, SCIM provisioning",
    href: "/sso",
    icon: Lock,
    group: "Enterprise",
    phase: 31,
  },
  {
    id: "franchise",
    label: "Franchise OS",
    description: "Multi-location performance and compliance",
    href: "/franchise",
    icon: Store,
    group: "Enterprise",
    phase: 32,
  },
  {
    id: "regions",
    label: "Multi-Region",
    description: "Global regions, data residency, latency routing",
    href: "/regions",
    icon: Globe,
    group: "Enterprise",
    phase: 33,
  },
  {
    id: "marketplace",
    label: "Agent Marketplace",
    description: "Discover, install, and publish AI agents",
    href: "/marketplace",
    icon: ShoppingBag,
    group: "Enterprise",
    phase: 34,
  },
  {
    id: "analytics-v2",
    label: "Analytics 2.0",
    description: "Revenue, sales, ops, and AI workforce dashboards",
    href: "/analytics/v2",
    icon: BarChart3,
    group: "Intelligence",
    phase: 21,
  },
  {
    id: "ageb",
    label: "AGEB Blueprint",
    description: "Global Architecture & Engineering Blueprint status",
    href: "/platform/ageb",
    icon: BookOpen,
    group: "Enterprise",
    phase: "ageb",
  },
  {
    id: "engines",
    label: "Core Engines",
    description: "Identity, workflow, rules, finance, event engines",
    href: "/platform/engines",
    icon: LayoutGrid,
    group: "Enterprise",
    phase: "ageb-3",
  },
];

export const EXTENDED_NAV = PLATFORM_MODULES.map((m) => ({
  href: m.href,
  label: m.label,
  icon: m.icon,
}));
