import type { LucideIcon } from "lucide-react";
import {
  BarChart3,
  Bell,
  Brain,
  Building2,
  CreditCard,
  FileText,
  Hammer,
  Inbox,
  Kanban,
  Landmark,
  LayoutDashboard,
  Lock,
  MessageCircle,
  PenLine,
  Phone,
  Plug,
  Rocket,
  ScrollText,
  Shield,
  ShoppingBag,
  Sparkles,
  Users,
  Video,
  Wallet,
  Workflow,
  Handshake,
  Gift,
} from "lucide-react";

export type PlatformModule = {
  id: string;
  label: string;
  description: string;
  href: string;
  icon: LucideIcon;
  group: "Core" | "Revenue" | "Intelligence" | "Operations" | "Enterprise";
  phase: number | string;
};

/** Phase 1–10 modules from os-new.txt */
export const CORE_MODULES: PlatformModule[] = [
  {
    id: "dashboard",
    label: "Founder Dashboard",
    description: "Revenue, pipeline, projects, AI workforce, Copilot",
    href: "/dashboard",
    icon: LayoutDashboard,
    group: "Core",
    phase: 12,
  },
  {
    id: "help",
    label: "Help & Product Tour",
    description: "Guided tour and 90-second live demo from the header",
    href: "/dashboard?help=open",
    icon: Sparkles,
    group: "Core",
    phase: "help",
  },
  {
    id: "workforce",
    label: "AI Team",
    description: "Chat, jobs, approvals, and AI employees",
    href: "/workforce",
    icon: Sparkles,
    group: "Core",
    phase: 1,
  },
  {
    id: "knowledge",
    label: "Knowledge Hub",
    description: "Upload, search, RAG Ask, Company Brain",
    href: "/knowledge",
    icon: Brain,
    group: "Core",
    phase: 2,
  },
  {
    id: "crm",
    label: "CRM",
    description: "Leads, contacts, deals, AI scoring",
    href: "/crm",
    icon: Building2,
    group: "Core",
    phase: 3,
  },
  {
    id: "whatsapp",
    label: "WhatsApp OS",
    description: "WhatsApp business inbox, outbound, and webhooks",
    href: "/whatsapp",
    icon: MessageCircle,
    group: "Core",
    phase: "9b-wa",
  },
  {
    id: "whatsapp-manage",
    label: "WhatsApp Manager",
    description: "Templates, business profile, and WABA phone assets",
    href: "/whatsapp/manage",
    icon: MessageCircle,
    group: "Core",
    phase: "9b-wa",
  },
  {
    id: "inbox",
    label: "Unified Inbox",
    description: "Legacy multi-channel inbox (hidden from primary nav)",
    href: "/inbox",
    icon: Inbox,
    group: "Core",
    phase: "9b",
  },
  {
    id: "voice",
    label: "Voice OS",
    description: "AI calling, dialer, call log, and Twilio voice",
    href: "/voice",
    icon: Phone,
    group: "Core",
    phase: "9b-voice",
  },
  {
    id: "projects",
    label: "Project OS",
    description: "Kanban boards, tasks, delivery tracking",
    href: "/projects",
    icon: Kanban,
    group: "Core",
    phase: "1b",
  },
  {
    id: "workflows",
    label: "Workflows",
    description: "BDM playbooks — outreach, follow-ups, meetings, handoffs",
    href: "/workflows",
    icon: Workflow,
    group: "Core",
    phase: "1c",
  },
  {
    id: "build",
    label: "Build OS",
    description: "Site preferences → AI plan → approve before generation",
    href: "/build",
    icon: Hammer,
    group: "Core",
    phase: "siteos-1",
  },
  {
    id: "launch",
    label: "Launch OS",
    description: "Idea → full business OS — industry, buddies, workflows (AGEB V11)",
    href: "/launch",
    icon: Rocket,
    group: "Core",
    phase: "ageb-11",
  },
  {
    id: "team",
    label: "Team",
    description: "Directory, channels, notes, activity",
    href: "/team",
    icon: Users,
    group: "Core",
    phase: 6,
  },
  {
    id: "integrations",
    label: "Integrations",
    description: "Gmail, Slack, Stripe, WhatsApp connections",
    href: "/integrations",
    icon: Plug,
    group: "Core",
    phase: 8,
  },
  {
    id: "communications",
    label: "Communications",
    description: "Notifications, alerts, AI digest",
    href: "/communications",
    icon: Bell,
    group: "Core",
    phase: 9,
  },
  {
    id: "analytics",
    label: "Analytics",
    description: "Executive charts — revenue, pipeline, ops, AI",
    href: "/analytics",
    icon: BarChart3,
    group: "Core",
    phase: 10,
  },
  {
    id: "settings",
    label: "Settings & RBAC",
    description: "Organizations, workspaces, roles",
    href: "/settings",
    icon: Shield,
    group: "Core",
    phase: 5,
  },
];

export const PLATFORM_MODULES: PlatformModule[] = [
  {
    id: "billing",
    label: "Billing",
    description: "Plans, subscriptions, usage tracking, and trials",
    href: "/billing",
    icon: CreditCard,
    group: "Revenue",
    phase: 11,
  },
  {
    id: "writing",
    label: "AI Writing Studio",
    description: "Proposals, emails, blogs, LinkedIn posts, SOPs",
    href: "/writing",
    icon: PenLine,
    group: "Intelligence",
    phase: 13,
  },
  {
    id: "meetings",
    label: "Meetings",
    description: "Transcript upload, summaries, tasks, follow-ups",
    href: "/meetings",
    icon: Video,
    group: "Intelligence",
    phase: 14,
  },
  {
    id: "sops",
    label: "SOP Engine",
    description: "Create, store, execute, and version SOPs",
    href: "/sops",
    icon: ScrollText,
    group: "Operations",
    phase: 18,
  },
  {
    id: "proposals",
    label: "Proposals",
    description: "Sales proposals with branding and export",
    href: "/proposals",
    icon: FileText,
    group: "Revenue",
    phase: 19,
  },
  {
    id: "finance",
    label: "Finance OS",
    description: "Ledger, P&L, balance sheet, invoices, budgets, AI CFO",
    href: "/finance",
    icon: Wallet,
    group: "Revenue",
    phase: 28,
  },
  {
    id: "payroll",
    label: "Payroll OS",
    description: "UK PAYE/NI payroll runs, payslips, ledger posting",
    href: "/payroll",
    icon: Landmark,
    group: "Operations",
    phase: "ageb-3",
  },
  {
    id: "hr",
    label: "HR OS",
    description: "ATS, onboarding, performance, learning",
    href: "/hr",
    icon: Landmark,
    group: "Operations",
    phase: 29,
  },
  {
    id: "autonomous",
    label: "Autonomous Agents",
    description: "Goal engine, task planning, orchestrator, approvals",
    href: "/workforce/jobs",
    icon: Sparkles,
    group: "Intelligence",
    phase: 30,
  },
  {
    id: "sso",
    label: "Enterprise SSO",
    description: "SAML, OIDC, OAuth, SCIM provisioning",
    href: "/sso",
    icon: Lock,
    group: "Enterprise",
    phase: 31,
  },
  {
    id: "affiliate",
    label: "Partner & Affiliate",
    description: "Referral links, commissions, regional caps, payouts",
    href: "/affiliate/dashboard",
    icon: Handshake,
    group: "Enterprise",
    phase: "GTM",
  },
  {
    id: "affiliate-admin",
    label: "Affiliate Admin",
    description: "Hierarchy tree, approvals, regional rate matrix, payouts",
    href: "/affiliate/admin",
    icon: Handshake,
    group: "Enterprise",
    phase: "GTM",
  },
  {
    id: "referrals",
    label: "Referrals",
    description: "Customer affiliate opt-in and income tracking",
    href: "/referrals",
    icon: Gift,
    group: "Revenue",
    phase: "GTM",
  },
  {
    id: "marketplace",
    label: "Agent Marketplace",
    description: "Discover, install, and publish AI agents",
    href: "/marketplace",
    icon: ShoppingBag,
    group: "Enterprise",
    phase: 34,
  },
];

export const EXTENDED_NAV = PLATFORM_MODULES.map((m) => ({
  href: m.href,
  label: m.label,
  icon: m.icon,
}));
